import GlobalState from "@/context";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";

export const metadata = {
  title: "Blackable",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <GlobalState>
          <Navbar />
          {children}
        </GlobalState>
      </body>
    </html>
  );
}
